try {
    6 / 0;
}
catch (err) {
    console.log("error is " + err);
}
finally {
    console.log("I will execute always");
}
